version: '3.4'

services:
  soundex:
    image: soundex
    build:
      context: .
      dockerfile: ./Dockerfile
    # install poetry and prevent image from exiting
    command: /bin/sh -c "poetry install && while sleep 1000; do :; done"
    volumes:
        - ./:/app
